Refactors ruby layer
battlemidget/juju-layer-ruby pull request #16
Opened 2019-09-05 03:28 UTC by battlemidget

- Compatibility with previous layer retained
- Will install via snapstore if snap-version is set and no ruby-version set,
  otherwise ruby-version takes precedence
- Add travis-ci, linting, black formatting
- Removed http/s-proxy from config as commands will now inherit from host os
  environment variables

Signed-off-by: Adam Stokes <battlemidget@users.noreply.github.com>

2019-09-05 03:29 UTC, battlemidget commented
ref #15, @mthaddon do you have a charm I can include in this repo for integration testing? Would also like a review on this PR

2019-09-05 14:50 UTC, mthaddon commented
Per discussions IRL, probably best to use the ubuntu charm and install ruby as an integration test.

2019-09-06 09:32 UTC, stub42 requested changes
This looks good.

I don't know what our requirements are here, but consider making the snap install the default, and consider dropping the non-snap install entirely. Ideally this implements best practice, and ideally there is e is only one best practice rather than two bestish practices.

2019-09-06 09:32 UTC, stub42 commented on lib/charms/layer/ruby.py
> +        return
You need to catch 'not is_snap_install and not ruby-install-version' here, or the later steps will explode if someone set ruby_install_version to the empty string (expecting a default or latest version or similar).

2019-09-06 09:32 UTC, stub42 commented on lib/charms/layer/ruby.py
> +    version = config.get("ruby-version", "2.6.4")
This doesn't work as you expect, as the default will never be used. config['ruby-version'] always contains a value (even if None or the default '').

Instead:
version = config['ruby-version'] or '2.6.4'

2019-09-06 12:55 UTC, battlemidget commented
I would prefer to just stick with snaps, @mthaddon any objections? And if so would layer-snap cover our needs with some helpers wrapped around bundler and gem?

2019-09-06 13:49 UTC, mthaddon commented
I don't have any objections to snaps only.

I don't know enough about the details to know if layer-snap with some helpers wrapped around bundler and gem would work, but it's quite possible it might.

2019-09-06 13:50 UTC, battlemidget commented
Cool, ill update the PR

2019-09-10 03:34 UTC, stub42 approved these changes
This all looks good to me.

While this is a backwards incompatible change, I don't think many charms will be affected and think that in this case it is better to tear the band-aid off quickly.

2019-09-10 03:36 UTC, stub42 commented on layer.yaml
> +      - git
Do you still need wget and/or git ?

2019-09-10 10:31 UTC, merged